cache_root: "/tmp/kandinsky2"
output_dir: ""
placeholder_token: "mypet"
initializer_token: "pet"
log_image_frequency: 250
log_embed_frequency: 250
img_size: 512
train_batch_size: 1
steps: 2500
positive_classes: ["pet"]
seed: 0
live_negatives: True
image_feature: True
optimize_in_text_space: True
pos_to_neg_loss_factor: 1.0
pos_image_embedded: False
optimize_in_image_sapce_for_positive: True
min_cosine_thr: 0.2
max_cosine_thr: 0.28
learning_rate: 0.0001
center: False
num_knn_class: 10